### PR TITLE
Add support for an interactive shell mode

### PR DESCRIPTION
**Pull request by pasky**

### CODE REVIEW

**Review by KPilnacek — COMMENTED** [review]
consider adding history (arrows did not work for me in the interactive shell) and autocompletion enabled shell

**Review by KPilnacek — CHANGES_REQUESTED** [review]
please fix linting issues: https://travis-ci.com/rossumai/elisctl/jobs/174911320

**Comment by qiq** [comment]
What is a use-case for this?

**Comment by pasky** [comment]
Usecase: Mainly in the Windows context, provide an "app" that opens by click and stays open rather than having to fuss around with `cmd.exe`.

**Comment by pasky** [comment]
I fixed the lint error, sorry about that. Didn't figure out how to resolve the review yet.

**Comment by pasky** [comment]
Regarding arrows and tab completion - actually, that's really weird as both works for me!! Does it just write escape sequences for you? Do you have click-shell==1.0 installed?

**Review by KPilnacek — APPROVED** [review]

**Comment by KPilnacek** [comment]
> Didn't figure out how to resolve the review yet.

The reviewis to be resolved by the reviewer 🙂

**Pull request merged**
